### ISSUE TITLE
Allow to set max image size

### ISSUE THREAD

**Issue by DanielMuller** [DanielMuller/koken-plugin-photoswipe#11]
Add a setting in plugin.json
{
"label": "Max Size",
"type":"slider",
"min":800,
"max":2048,
"value":2048,
"step":20,
"suffix":"px"
}

Don't populate PS object for images bigger than this size.

**Comment by thedailynathan** [comment]
Is there a reason the maximum is hard-coded to 2048? It would be useful to allow higher for larger monitors.

**Comment by DanielMuller** [comment]
The reason being that Koken's biggest version generated is 2048px (named huge).
For screens bigger that 2048px, the huge.2x version (4096px) would be served. The plugin can't serve the original, since the dimensions of the original aren't known.
In your use case, what image is served by Koken's Lightbox?
