### ISSUE TITLE
Photoswipe in OxyGen

### ISSUE THREAD

**Issue by BlackSkorpio** [DanielMuller/koken-plugin-photoswipe#12]
Hi there Daniel!
I'm trying to enable PhotoSwipe in my custom theme, with no avail! :(

I tried to define the DOM: a.k-link-lightbox but it dosent help
http://varoystrand.se/album/free-style/

I cleared the system cache as advised...

Do you think you could point me in the right direction, or am I "smoked"?

Would love to be able to support your plugin in my theme...
Source code for the theme can be found here: https://github.com/BlackSkorpio/OxyGen

(A small side note:
I have taken the liberty to ad your plugin to our "Plugin forum: http://kokensupport.varoystrand.se/viewforum.php?f=17 )

**Comment by DanielMuller** [comment]
On your page, I see 2 javascript errors:
1/
```str = str.replace("<span class="k-infinite-load">", "");```
I didn't find this in your repo. But you forgot to escape the double quotes.

2/
```$(".cover_inside h1").fitText(1.2, { minFontSize: 'px', maxFontSize: 'px' });```
The fitText method is unknown. I created a pull request (BlackSkorpio/OxyGen#7) to add the missing library.

Once this fixed, I was able to use my plugin, but didn't test heavily. There are still some graphical glitches (z-index?). Better to treat them in separate issues.

**Comment by BlackSkorpio** [comment]
Will look in to issue 1 as soon as I'm on my computer again...
The pull request is merged!

Thanks for taking time to help out! :D 

The z-index should be easy to resolve.

**Comment by BlackSkorpio** [comment]
I think i managed to fix the glitches now.
PhotoSwipe is runnings smoothlie on my site as of now

(1/ was a "left over" from some experiments...

Added: ` 'oxygen' => 'a.k-link-lightbox' ` to `$triggerEls` in plugin.php before I enabled photoswipe now and it worked with out any "hick-ups".
