### ISSUE TITLE
Help wanted for use with Elementary Theme

### ISSUE THREAD

**Issue by SveBel** [DanielMuller/koken-plugin-photoswipe#14]
Thanks a lot Daniel for your great work increasing the lightbox speed for Koken.
I've tried to use it with Kokens Elementary theme, but not to the best results so far:
- If I use the default trigger (a.thumb) then the lightbox opens already on the page where all albums are displayed as thumbs. In the lightbos then I can see only the thumb title images. 
- If I use the trigger a.k-link-lightbox then clicks on thumbs work correctly (don't open the lightbox) but clicking on the link labeled "View in lightbox" doesn't activate the photoswipe lightbox, only the standard one. However, when I click inside the single image (when the magnifying glass cursor is displayed), then the photoswipe lightbox opens. But then, when using a cursor right, the lightbox closes as the event obviously is handled outside the lightbox first.

My desired behavior is that when I see a single image (with some thumbs and tags in a second cloumn to the right of it - see screenshot) then clicking on the link labeled "View in lightbox" should activate the new photoswipe lightbox - simply everytime when the "old" lightbox is called.
![lightbox](https://cloud.githubusercontent.com/assets/14220144/9792776/3aa6720e-57e2-11e5-954c-37f9b7a22dc3.png)

I would really appreciate it if you could give me some instructions as to how I can get the desired behavior. I've been searching and trying several things for hours but to no avail as I'm not familiar with this kind of programming. Although I've done programming befiore, unfortuneately I'm a newbie if it comes to website programming...
Thanks a lot,
Sven.

**Comment by DanielMuller** [comment]
I don't have experience with "Elementary". I will need to install this theme to see how this works.

**Comment by DanielMuller** [comment]
Hi Sven,
The way you want to use this plugin is not ideal. This plugin is only able to parse the HTML DOM and display images of already loaded content. In your case, only 1 image is available in the HTML DOM, Photoswipe can only load this image and you won't be able to flip through several images. 
That's the reason behind opening the Lightbox from the "grid view" and not the "image view".

Koken's Lightbox on the other hand is able to fetch the image list again, and show all images.

I still addressed your issues in [release v1.6.2](https://github.com/DanielMuller/koken-plugin-photoswipe/releases/v1.6.2).
The default behaviour is still opening from the grid view, but if you change the selector to *a.k-link-lightbox* like you did, Photoswipe will open by clicking the image as well as the "View in lightbox" link.
I also disabled Koken's key bindings when Photoswipe is open.

**Comment by SveBel** [comment]
Hi Daniel,

thanks very much for your time and effort you took in order to answer my 
question.
It is much appreciated.
I will test your improvements soon.

Be blessed
Sven

Am 2015-09-24 um 16:08 schrieb Daniel Muller:
