### ISSUE TITLE
show captions

### ISSUE THREAD

**Issue by hamiltoncody** [DanielMuller/koken-plugin-photoswipe#15]
It there away to get the image cations to show at the bottom?

**Comment by hamiltoncody** [comment]
Also was noticing that it goes through the image order in a different order than the koken lightbox. Basically it doesn't seem to follow the order that I have in my albums. Thoughts?

**Comment by DanielMuller** [comment]
This plugin is only able to access what is displayed on the HTML page and can't access data in the Database in the same way Koken's Lightbox plugin does. Koken plugins have very limited access to the underlying data.
The captions are not available in the HTML layout (at least not with the default themes) and therefore I can't fetch them to display.

For your second comment, what theme are you using? If you are using a theme that makes use of the Pillar JS Library, the plugin can only "see" the content that is available before Pillar re-orders them.

**Comment by hamiltoncody** [comment]
I was trying it with the Regal 2 theme so I guess Pillar is the problem then. Bummer love the look of the newest versions of photoswipe so much more than the built in lightbox. Any thoughts on how to get it to work? Would I need to rebuild the theme to use masonry instead of pillar?

**Comment by DanielMuller** [comment]
I don't think changing the JS library would change anything. The plugin was mainly written with Axis1 in mind (awful standard html grid layout).
Perhaps parsing DOM after Pillar did his job could solve the issue. But my JS skills are not good enough to do this.

**Comment by georg90** [comment]
Any progress on how to implement this into the theme? I like to see captions as well :)

**Comment by DanielMuller** [comment]
Fixed by #17

**Comment by georg90** [comment]
thanks! :)
