### ISSUE TITLE
Custom skin/css

### ISSUE THREAD

**Issue by BlackSkorpio** [DanielMuller/koken-plugin-photoswipe#19]
Hi there Daniel.
I world like to make some changes to the default skin, and was trying (as you wrote in the readme) creating a default-skin.css in custom/default-skin/

After doing my edits (just some small tweaks) I emptied the cache of Koken and in my browser: but PhotoSwipe is still using the pswp/default-skin/default-skin.css

What have I missed here?

**Comment by DanielMuller** [comment]
What you did is right. Perhaps there is still some other caching elsewhere, or Koken didn't clean out it's cache fully.
Can you try deleting manually the storage/cache/site folder?

**Comment by BlackSkorpio** [comment]
Sorry Daniel, it turned out that me host deployed a Varnish caching for there shared hosting...
It's working as expected...

(A small side note:
I'm adding support for the both the simple caption as well as the EXIF in OxyGen v3)
