### ISSUE TITLE
Images opened in wrong order on Regale 2

### ISSUE THREAD

**Issue by pauschpage** [DanielMuller/koken-plugin-photoswipe#20]
Hi there!

I love your photoswipe plugin, but when Regale 2 theme is used the images open in a wrong order.
They open vertically in each column - so actually not the next image is displayed.

See christian-schartner.at/gallery

**Comment by DanielMuller** [comment]
Sadly there is not much I can do.
This plugin is parsing the HTML DOM content, and doesn't have access to Koken's API.
Koken's V2 themes are using a Javascript Library called Pillar that reorganise the images into columns and therefore changing the order in which the images appear in the DOM.
