### ISSUE TITLE
Disabling the zoom function

### ISSUE THREAD

**Issue by BlackSkorpio** [DanielMuller/koken-plugin-photoswipe#21]
Hi there Daniel.
Is there any way that I can disable the "zoom-in" function?

I don't mind changing it in the JS, as long a you can give me pointers to how and where... 

Maybe adding this as an option in coming releases?

**Comment by DanielMuller** [comment]
Photoswipe accepts [options](http://photoswipe.com/documentation/options.html) for this: `maxSpreadZoom` and perhaps `getDoubleTapZoom`
I keep most of the default options, you can add more options to pass to Photoswipe, by adding them to the `option` hash: [pswp.js](https://github.com/DanielMuller/koken-plugin-photoswipe/blob/201fdf8173034706b08e40c3a74a15677847c823/src/pswp.js#L91-L118)

**Comment by BlackSkorpio** [comment]
Thnx, will have a look at what I can do with it :)
