### ISSUE TITLE
Lightbox URLs

### ISSUE THREAD

**Issue by daywa1ker** [DanielMuller/koken-plugin-photoswipe#28]
Hello,

First off, thanks for the solution to Koken's lack of lightbox preloading. This is a dramatic improvement, performance-wise.

I'm trying to make this work on a friend's site, which has been up for awhile. The issue I'm running into is that the nature of the URLs has changed dramatically. While my preference is for the older URLs (domain.com/albums/[album-name]/content/[image-name]), I could live with the new URLs if there's a way to redirect the old URLs to the new. Any idea how this might be possible?

I'm no PHP expert, but if you can point me in the right direction I can probably figure it out.

Thanks!

Joe

**Comment by DanielMuller** [comment]
The url is defined by Photoswipe, and there is no option to override the format.
Even if possible, using the same url as the default lightbox, would introduce too many possible wrong behaviours, specially on direct content linking.

On 4 Mar 2016 8:23 am, daywa1ker <notifications@github.com> wrote:

Hello,

First off, thanks for the solution to Koken's lack of lightbox preloading. This is a dramatic improvement, performance-wise.

I'm trying to make this work on a friend's site, which has been up for awhile. The issue I'm running into is the nature of the URLs has changed dramatically. While my preference is for the older URLs (domain.com/albums/[album-name]/content/[image-name]), I could live with the new URLs if there's a way to redirect the old URLs to the new. Any idea how this might be possible?

I'm no PHP expert, but if you can point me in the right direction I can probably figure it out.

Thanks!

Joe
