### ISSUE TITLE
Installation causes koken to stop loading

### ISSUE THREAD

**Issue by th1L0** [DanielMuller/koken-plugin-photoswipe#3]
Hi Daniel,

great plugin that your are providing - at least as it is working on your site ;)

My issue: After installing (aka uploading to plugin-folder), my site is not loading any more and my admin console ist just plain black (no menus etc.).

Any idea regarding a possible reason for this?

Thx lot, Thilo

**Comment by DanielMuller** [comment]
Just tried to install the plugin "fresh", and didn't run into any trouble.
Have you tried emptying "api cache" and "site cache" before installing the plugin? Browser cache may help too.

If this doesn't work, you would need to turn on PHP debugging (in api.php) to get an idea of the cause.

**Comment by th1L0** [comment]
Cleaned both caches (api + site) but still same behavior.

Even stranger: It works on my local MAMP installation.

As I don't have any experience in web development and there don't know anything about php debugging, it looks a bit as if my road ends here ;) and I will have to live with the common annoying koken lightbox on my site (btw: thilomeyer.me).

But thanks anyway for trying to help!

**Comment by th1L0** [comment]
Hmm, I am sorry but I have to come to you.

I tested the plugin with a couple of themes on my local installation and it is just working with some of them:

working: Axis (don't have Axis 2), Ensemble, Elementary, Boulevard
not working: Madison 2, Regale 2

Maybe this is an indicator for my problem above, too?

**Comment by DanielMuller** [comment]
Pattern seems to indicate it is linked to V2 themes. I don't have any of the V2 themes, therefore can't pin point the issue.
If you can send me the themes files (email to daniel@ctrlaltdel.ch, avoid putting paid themes in Github), I can take a look.

**Comment by th1L0** [comment]
You've got mail.

**Comment by DanielMuller** [comment]
It seems there are 2 issues here:
1. Black screen in admin
2. Photoswipe not beeing used in Regale 2/Madison 2

For the 1st point, I have no clue. I was unable to reproduce.
For the 2nd point, the default DOM elements where not assigned. I fixed than in [V1.4](https://github.com/DanielMuller/koken-plugin-photoswipe/releases/tag/V1.4):
