### ISSUE TITLE
Regular fade transition to accomodate cropped thumbs?

### ISSUE THREAD

**Issue by thedailynathan** [DanielMuller/koken-plugin-photoswipe#31]
The usage of the plugin on themes with cropped thumbnails causes some UI wonkiness, as the initial crop available (and used for expansion) can be a completely different aspect ratio from the original (landscape crop for a portrait full-size looks especially bad). Currently it just gets stretched out for a split second, then "pops" in the correct image when it loads.

Could there be an option for a very basic loading icon + fade in transition?

**Comment by thedailynathan** [comment]
I did find the option `showHideOpacity: false` which can be added into the options that instantiate Photoswipe (right above `preload:[5,10]`) that handles the first part of this issue by fading transition.

There is still a "snap" of some kind due to cropped photos however. Have not been able to figure out this bug so far.

**Comment by DanielMuller** [comment]
The first image to be loaded, is the lowres one from the thumbnail page. The reason for this, is to show something before loading the hires one.
I didn't think of the cropped image case. One way to solve this, would be to not show the lowres. It would show a blank screen while the hires is loading.
I will do some tests and try figure out how to fix this.
