### ISSUE TITLE
Lightbox deeplinks should repopulate meta tags?

### ISSUE THREAD

**Issue by thedailynathan** [DanielMuller/koken-plugin-photoswipe#32]
Not sure if this is possible (or maybe requires some config the user can do on template side). Currently it is possible to deeplink to an album, but the meta tags (such as og:image for social media preview scraping) are not up to date with the featured photo.

Could probably do a search for the meta tag with this property and update it as the slideshow opens each image?

**Comment by thedailynathan** [comment]
but also might require storing the original value (such as featured album image) to restore it whenever slideshow is closed.

**Comment by thedailynathan** [comment]
Upon further research this doesn't seem possible via javascript, as scrapers like Facebook will not actaully execute it: http://stackoverflow.com/questions/3081004/update-facebook-open-graph-meta-tag-through-javascript

**Comment by DanielMuller** [comment]
The plugin has no access to images infos (Koken API), only to whatever is existing inside the album DOM.
Image URL would be a known info, to add it the Photoswipe template would need to be changed (https://github.com/DanielMuller/koken-plugin-photoswipe/blob/master/pswp/pswp.html) and the JS too (to fill the info in).
As you noticed, FB wants pure HTML and doesn't deal with JS. Another reason for not doing it, is that this plugin's job is to display the content in a better way to the user.
To deep link correctly, I would suggest you link to the detail URL of the "Koken full sized Image"
