### ISSUE TITLE
Only 10 images showing up in photoswipe.

### ISSUE THREAD

**Issue by lxlarcadelxl** [DanielMuller/koken-plugin-photoswipe#33]
Hello Daniel,

i dont know if only i have the problem so i try to explain.
i use axis 2 theme and integrated photoswipe into koken.
Now i have an album with about 19 images but photoswipe shows just 10 images.
if i press on the 11th image it opens in the koken viewer which i dont really like.

die i have to setup and option somewhere so photoswipe accepts more than 10 images ?

Very good job on this plugin i really love it.

I would be thankful for any help.
Marcus

**Comment by DanielMuller** [comment]
Do you have a page link? I don't have Axis2 to test this.

**Comment by lxlarcadelxl** [comment]
Ok I think I have a theory. On my phone it loads 1/10 now. But if I scroll down and it loads more images then photoswipe finds them. What can I do in this case? 
You can check it here
http://photozirkel.de/galerie/albums/nekropolis/

**Comment by lxlarcadelxl** [comment]
Oh and thanks for your reply and help. I think it is not much different to axis 1

**Comment by DanielMuller** [comment]
V2 templates versions are loading data through Javascript, and only a subset of the album is available in the initial HTML. Initial amount of loaded images depends on screen size.
Your 19 images are loaded fine on a desktop screen, but on mobile only 10.
This plugins is only able to know images that are loaded in the initial HTML code. It can't fetch the same data as Koken's native code. Mainly because Koken didn't release any documentation for their API.
You could change your Axis2 config or code, to load more data at once. But I don't know where this needs to be changed.

**Comment by lxlarcadelxl** [comment]
Hey Daniel,
Thanks for your answer and time again.
I would love to use the photoswipe plugin. 
I would even burn the money for the axis 2.
Is there a chance i can download the Axis 1 Theme somewhere ? Or do you have the old theme somewhere. Koken doesn't offer it anymore to download so it is hard to find. 
Maybe you have an idea.

You can close this issue then because it doesn't seem to be an issue with your plugin.

best wishes to you

**Comment by lxlarcadelxl** [comment]
Okay i edited the info.json and raised the load_limit_album value to a max of 80. So it works with up to 80 images per album now.

**Comment by DanielMuller** [comment]
Good news! Are you still in need for Axis1? Or did this change solve your issue?

**Comment by lxlarcadelxl** [comment]
Hi Daniel,
Yes i would love to have a look on it because with my solution I'm limited to 80 images per album. 

Thanks a lot. 
I can give you my email if you need it. 

Nice news
Have a nice day
Marcus

**Comment by DanielMuller** [comment]
Axis 1 has the same kind of issue, it shows maximum 100 images per page. I will find an Axis1 theme to share

**Comment by lxlarcadelxl** [comment]
But at least I think it's better to customize than axis 2
Thanks a lot for your support and time on this.

**Comment by DanielMuller** [comment]
You can get it here: https://we.tl/5tVwZ5lCq4

**Comment by lxlarcadelxl** [comment]
Hey Daniel i appreciate your help even if it is not a problem with your koken integration of the plugin.
But i can verify that your plugin works with a little modification on Axis 2 (only limit are 80 images per album, which should be enough normally). 

Thanks a lot for your support and all the best for you!
