### ISSUE TITLE
Incorrect sequence order for regale (advance gid instead of pid)

### ISSUE THREAD

**Issue by marcosmontero** [DanielMuller/koken-plugin-photoswipe#36]
Hi,

The sequence of photos in the photoswipe gallery does not follow the sequence of the album in Regale2, as it moves vertically through the column rather than horizontally. Is there a way to get around this issue? Could the plugin be extended so that the left/right nav buttons do support the Regale sequence order. 

Thanks,
Marcos

**Comment by DanielMuller** [comment]
Duplicate of #20 
The plugin parses the HTML generated by the templates view, and doesn't know about layout. It known only about the order the files are referenced in the source.
