### ISSUE TITLE
Rating Plugin Support possible?

### ISSUE THREAD

**Issue by NiTRoeSE** [DanielMuller/koken-plugin-photoswipe#37]
Hi, first..thanks for your work on this plugin, love it !
Is it possible to integrate a "Rating Plugin" support ?
Maybe so that is possible to give a Rating in the photo swipe box ?
Rating heart can maybe positioned in the same place next to zoom in /out / fullscreen menu ?

Thanks & regards

**Comment by DanielMuller** [comment]
Hi NiTRoeSE,
Depends on how Koken has implemented it. Possibilities in plugins are very limited, specially there is no access to Lens functionality. It can only work if the Rating Plugin provides a public API.
I don't have access to any documentation or implementation of their Rating Plugin. Do you have an URL where it is running?

**Comment by NiTRoeSE** [comment]
Hi Daniel, thanks for your fast reply.
I updated my theme in the last day to get ready for the rating plugin and implemented it into my site.
All over it works fine.
I have also tried to get it working in the photo swipe box, but it doesn't work.

I have added it in the same way like the exif data to show up in the photo swipe box, but it works not really, all what is displayed is the little "i like heart" but the counter is not shown and the "click on it" don't work.

At the whole site it works with the token `<koken:rating>` but not in the photoswipe box.
```
<koken:img  class="preview" lazy="true" />
                                         <div class="item-caption" style="display: none">
                                                <koken:time data="content.captured_on" show="date"/>
                                                |
                                                <koken:exif>

                                                        <koken:not empty="exif.model">
                                                        {{ exif.model }},
                                                        </koken:not>
                                                        <koken:not empty="exif.exposure">
                                                        {{ exif.exposure }},
                                                        </koken:not>
                                                        <koken:not empty="exif.aperture">
                                                        {{ exif.aperture }},
                                                        </koken:not>
                                                        <koken:not empty="exif.focal_length">
                                                        {{ exif.focal_length }},
                                                        </koken:not>
                                                        <koken:not empty="exif.iso_speed_ratings">
                                                        {{ exif.iso_speed_ratings }}
                                                        </koken:not>
                                                        <koken:rating>
                                                        <p> {{ rating }}</p>
                                                        </koken:rating>

                                                </koken:exif>

                                                </div>
```

Dokumentation URL: (there is no api but maybe a other way to let it function properly in the box?)

http://help.koken.me/customer/portal/articles/828690-lens-tags#kokenrating

Website URL to it see it in action:

https://medialyse-photography.de

regards

**Comment by DanielMuller** [comment]
Thanks for providing an example. I tried to mimic what Koken does in its Lightbox.
Rating should display, not sure about the ability to add a new like from Photoswipe. I let you test this.

**Comment by NiTRoeSE** [comment]
Hi Daniel, thank u very much for this super fast christmas present :D
The new version runs fine so far except of one thing...
The "Heart" button in the box can trigger new likes..this works well and is fantastic, but he likes the false image..at my site its so that when i open up photo 3 of an album then the box shows me the likes from photo 4, if i like photo 3 than photo 4 becomes the like.

A good exsample ist the following album...

https://medialyse-photography.de/albums/night-stars/

The milky way panorama (photo number 4) have 2 likes...if u open this in the box it shows 0 likes, but if u open the "tower meets thunderbolt" photo (number 3) u can see the likes from the panorama.

**Comment by DanielMuller** [comment]
I opened issue #39 to track this.
