### ISSUE TITLE
Regale2 limited to 30 images

### ISSUE THREAD

**Issue by marcosmontero** [DanielMuller/koken-plugin-photoswipe#38]
Hi Daniel,

I've noticed that the plugin would only load 30 images from a gallery that has just been opened by the user. If however more images are loaded (e.g. the user scrolls down through the gallery), these extra images would be indexed in the plugin.  Apologies if this has been asked before (I couldn't see it as  Closed Issue), but is there a way to circumvent this so that let's say 100 photos would be available in the DOM and hence available in the plugin from the start?

Many thanks for your ongoing help!
Marcos

**Comment by DanielMuller** [comment]
The plugin is only able to see what is rendered in the HTML DOM. Regale2 renders only 30 images, subsequent images are appended to the DOM via Javascript after scrolling.
If you scroll down to load the subsequent 30, you will notice that Photoswipe "sees" now 60 images.
This limit of 30 is hard-coded in the theme template, you can increase it by modifying *album.lens*, *contents.lens*, *favorites.lens*.

**Comment by marcosmontero** [comment]
Thanks a lot Daniel. I got it working! :)
