### ISSUE TITLE
Wrong image associated to rating

### ISSUE THREAD

**Issue by DanielMuller** [DanielMuller/koken-plugin-photoswipe#39]
The "Heart" button in the box can trigger new likes..this works well and is fantastic, but he likes the false image..at my site its so that when i open up photo 3 of an album then the box shows me the likes from photo 4, if i like photo 3 than photo 4 gets the like.

A good exsample ist the following album...

https://medialyse-photography.de/albums/night-stars/

The milky way panorama (photo number 4) have 2 likes...if u open this in the box it shows 0 likes, but if u open the "tower meets thunderbolt" photo (number 3) u can see the likes from the panorama.

**Comment by NiTRoeSE** [comment]
Thanks you ! :D
