### ISSUE TITLE
switching horizontal/vertical orientation problem in iOS 10

### ISSUE THREAD

**Issue by heyhenri** [DanielMuller/koken-plugin-photoswipe#42]
Hi, Photoswipe (thanks for this great plugin!) used to work just fine, but (i think since iOS 10.x) it has problems viewing the photos when the orientation of the device is changed, see photos. 
This goes for all of my 3 websites, using Koken 0.22.20 & 0.22.19 with Oxygen 3.2.2 & 3.3.0 theme and Photoswipe 1.7.7 & 1.7.8

iPhone 6s iOS 10.3.1
iPhone 5 iOS 10.3.1

iPad mini 1 with iOS 9.3.5 has no problems

thanks, Henri

![3](https://cloud.githubusercontent.com/assets/27432574/25011269/139033b2-206d-11e7-8e8b-b9f44a296e77.PNG)
![1](https://cloud.githubusercontent.com/assets/27432574/25011270/13b7e5ba-206d-11e7-9d03-489419b2dbf4.PNG)
![2](https://cloud.githubusercontent.com/assets/27432574/25011271/13bb3b48-206d-11e7-8355-59dc2289394e.PNG)

**Comment by DanielMuller** [comment]
Hi @heyhenri , I am not [Photoswipe](https://github.com/dimsemenov/PhotoSwipe), I just embedded Photoswipe into a Koken plugin :wink: 
The problem has been fixed upstream. Updated to latest Photoswipe in release [1.7.9](https://github.com/DanielMuller/koken-plugin-photoswipe/releases/tag/v1.7.9).
No device to to test, I hope this fixes your issue.

**Comment by heyhenri** [comment]
Sorry, i was not sure on who's door I had to knock :) 
But, problem fixed, thanks a lot!
