### ISSUE TITLE
Image URLs

### ISSUE THREAD

**Issue by spiffin** [DanielMuller/koken-plugin-photoswipe#43]
Excellent plugin - thank you.

Is there any way to change the image URLs when viewing a slideshow? They are currently formatted similar to:

http://mydomain.com/albums/my-album/#&gid=1&pid=000-014-p1000657

Could they reference the image title rather than the file name? e.g.:

http://mydomain.com/albums/my-album/#my-image-title

Thanks

**Comment by DanielMuller** [comment]
The pid value is just to know which image file to open by default, I used the file name as a kind of unique id.
You can alter to code to use any kind of identifier, but I wouldn't use a title, since title might change and then URL's previously stored won't point to anything.

**Comment by spiffin** [comment]
Okay, thanks for the explanation.
