### ISSUE TITLE
Regale 2: Just 30 pictures beeing displayed

### ISSUE THREAD

**Issue by pauschpage** [DanielMuller/koken-plugin-photoswipe#46]
Hi There again.

I'm having another Issue with Regale 2 and Photoswipe,
just the first 30 pictures are being displayed on mobile (some of my galleries have 50 pictures).

Is this because of the way and order how Regale 2 loads the images?

Thank you,
Christian

**Comment by DanielMuller** [comment]
Yes, this has to do with how Regale2 loads the images. Same issue reported in #38
