### ISSUE TITLE
Plugin not injecting for me (Axis V1)

### ISSUE THREAD

**Issue by emory** [DanielMuller/koken-plugin-photoswipe#9]
Very weird — I have installed the plugin, enabled it, double-checked the more-info panes for defaults but my axis v1 theme is still loading the Koken lightbox. I see the pswp script is being fed to my browser but the photoswipe classes aren't being added to my HTML.

Not sure how to proceed but can follow directions. Site is ephemeral.be. I've purged system caches, switched themes back and forth.

**Comment by DanielMuller** [comment]
You need to define the DOM-element that holds your images. You renamed your theme from "axis" to "koephemeral". If you are using a copy of Axis, in the plugins settings set 'a.k-link-lightbox' as 'trigger element'

**Comment by emory** [comment]
ah-ha, thanks will confirm. didn't see any changes to trigger so assumed errything was copacetic.

**Comment by emory** [comment]
confirmed, closing. (thank you)
